### ISSUE TITLE
Reduce the mass

### ISSUE THREAD

**Issue by ff6347** [vogelino/molecular-networks-p5-algorithm#3]
I think your visual output needs some less circles. Add some whitespace

**Comment by vogelino** [comment]
[![v005 3](https://cloud.githubusercontent.com/assets/2759340/11172040/d679800e-8bfe-11e5-83f8-11fdf837de0a.png)](http://vogelino.github.io/molecular-networks-p5-algorithm/)
Okay I changed it. I think I'm quite satisfied with this result. What do you think?

**Comment by ff6347** [comment]
Way better. :-)
