### ISSUE TITLE
Dummy issue for hosting images

### ISSUE THREAD

**Issue by vogelino** [vogelino/molecular-networks-p5-algorithm#5]
![algorithm-01-explanation](https://cloud.githubusercontent.com/assets/2759340/11172457/384365a8-8c08-11e5-808b-890437f0858f.jpg)
![algorithm-01-result-1](https://cloud.githubusercontent.com/assets/2759340/11172458/38451db2-8c08-11e5-82db-7da10b04136d.jpg)
![algorithm-01-result-2](https://cloud.githubusercontent.com/assets/2759340/11172459/3849209c-8c08-11e5-9c10-c23d6c562707.jpg)
![algorithm-01-result-3](https://cloud.githubusercontent.com/assets/2759340/11172460/384ac5f0-8c08-11e5-8db5-c92f1633907a.jpg)
![algorithm-01-result-4](https://cloud.githubusercontent.com/assets/2759340/11172461/384d31a0-8c08-11e5-93df-ea8e9a9f4176.jpg)
![algorithm-01-result-5](https://cloud.githubusercontent.com/assets/2759340/11172463/385b821e-8c08-11e5-9137-8175c5409e05.jpg)
![algorithm-02-result-1](https://cloud.githubusercontent.com/assets/2759340/11172462/3859b682-8c08-11e5-849f-38c9d253bc23.jpg)
![algorithm-02-result-2](https://cloud.githubusercontent.com/assets/2759340/11172464/385e1dda-8c08-11e5-8388-50bfdc112763.jpg)
![algorithm-02-result-3](https://cloud.githubusercontent.com/assets/2759340/11172466/386565ea-8c08-11e5-949e-3fe9230932e3.jpg)
![algorithm-02-result-4](https://cloud.githubusercontent.com/assets/2759340/11172465/386510f4-8c08-11e5-854a-6f048071a187.jpg)
![algorithm-02-result-5](https://cloud.githubusercontent.com/assets/2759340/11172467/386dde5a-8c08-11e5-8abf-89331c124985.jpg)
![algorithm-02-result-6](https://cloud.githubusercontent.com/assets/2759340/11172469/38749362-8c08-11e5-8082-a470458637d7.jpg)
![algorithm-02-result-7](https://cloud.githubusercontent.com/assets/2759340/11172468/38730268-8c08-11e5-90cb-46a7971cb02d.jpg)
![algorithm-02-result-8](https://cloud.githubusercontent.com/assets/2759340/11172470/387d3c42-8c08-11e5-9252-0180d8b598b7.jpg)
![algorithm-02-result-9](https://cloud.githubusercontent.com/assets/2759340/11172471/387d8c7e-8c08-11e5-9e4b-ce1682d327f3.jpg)
![algorithm-02-result-10](https://cloud.githubusercontent.com/assets/2759340/11172472/388585b4-8c08-11e5-96b2-4e09f59a207c.jpg)
![algorithm-03-result-1](https://cloud.githubusercontent.com/assets/2759340/11172474/388d5528-8c08-11e5-9563-33b325425871.jpg)
![algorithm-03-result-2](https://cloud.githubusercontent.com/assets/2759340/11172473/388cfc9a-8c08-11e5-9d40-f12a03399caf.jpg)
![algorithm-03-result-3](https://cloud.githubusercontent.com/assets/2759340/11172475/38939546-8c08-11e5-98c5-6b88a4086aa4.jpg)
![algorithm-03-result-4](https://cloud.githubusercontent.com/assets/2759340/11172476/389481c2-8c08-11e5-9e6e-2da28e49acaf.jpg)
![algorithm-03-result-5](https://cloud.githubusercontent.com/assets/2759340/11172477/389bfd8a-8c08-11e5-9b34-75d24949ce7d.jpg)
![algorithm-03-result-6](https://cloud.githubusercontent.com/assets/2759340/11172479/38a60ff0-8c08-11e5-9cca-bf676e3fccde.jpg)
![algorithm-03-result-7](https://cloud.githubusercontent.com/assets/2759340/11172478/38a384ec-8c08-11e5-87dc-1095c32cef59.jpg)
![algorithm-03-result-8](https://cloud.githubusercontent.com/assets/2759340/11172480/38abef9c-8c08-11e5-9d31-68459d8cbc75.jpg)
![algorithm-03-result-9](https://cloud.githubusercontent.com/assets/2759340/11172481/38acb40e-8c08-11e5-9c7d-45ce13858e8c.jpg)
![algorithm-03-result-10](https://cloud.githubusercontent.com/assets/2759340/11172482/38b40b28-8c08-11e5-8947-2eefbf8ce59e.jpg)
![algorithm-03-result-11](https://cloud.githubusercontent.com/assets/2759340/11172483/38bb165c-8c08-11e5-9c8d-05a8e198af88.jpg)
![skizzen1](https://cloud.githubusercontent.com/assets/2759340/11172484/38be4c96-8c08-11e5-85ac-44668d431691.jpg)
![skizzen2](https://cloud.githubusercontent.com/assets/2759340/11172485/38c1cc2c-8c08-11e5-9007-05f5b08db69d.jpg)
![skizzen3](https://cloud.githubusercontent.com/assets/2759340/11172486/38c5c958-8c08-11e5-9f0e-bb51c89477bf.jpg)

**Comment by ff6347** [comment]
Why don't you host your images in your repo? You can grab them by getting the raw url and use them anywhere

**Comment by vogelino** [comment]
These are images for the documentation. As they don't relate to the code
directly I don't want to include them directly. By just dragging and
dropping them in a closed issue, I let github host them for me! :)

Le lundi 16 novembre 2015, Fabian Morón Zirfas notifications@github.com a
écrit :

> Why don't you host your images in your repo? You can grab them by getting
> the raw url and use them anywhere
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/vogelino/molecular-networks-p5-algorithm/issues/5#issuecomment-156910973
> .

## 

Sent from my phone. Please excuse my brevity.

**Comment by ff6347** [comment]
The documentation should not only be about code. Add them to your repo. It should contain everything. It's also easier for me later on to find things when they are in the repo. Maybe I need some of these images for another presentation. Having them hidden away in the issues is strange.

**Comment by vogelino** [comment]
Right, as you wish

**Comment by ff6347** [comment]
:+1: :smile:
