### ISSUE TITLE
Not possible to build nor run

### ISSUE THREAD

**Issue by ff6347** [vogelino/molecular-networks-p5-algorithm#6]
When I try to run it like mentioned in the README I get this error:  

[npm-debug.log.txt](https://github.com/vogelino/molecular-networks-p5-algorithm/files/467375/npm-debug.log.txt)

**Comment by ff6347** [comment]
Hm. I would love to include your project into the examples for my next seminar. Can you provide a bundled version of the script. Without styling just the to include a 500*500 canvas into this site?  http://fabianmoronzirfas.github.io/gestalten-in-code/

**Comment by vogelino** [comment]
Hi Fabian,

Das liegt eventuell an deine Node version. Es muss mit node v0.12.9 ausegführt werden. Das habe ich noch in der package.json, den .nvmrc und den README.md hinzugefügt.

Anbei ist ein zip mit der index.html und der bundle.js

[molecular-networks-p5-algorithm-bundled.zip](https://github.com/vogelino/molecular-networks-p5-algorithm/files/470911/molecular-networks-p5-algorithm-bundled.zip)

**Comment by ff6347** [comment]
Awesome thank you.

**Comment by ff6347** [comment]
hm. Adding the project to the site is somewhat impossible with 40000LOC. Would be create to have a simple version of it. Currently it is represented as an image. http://fabianmoronzirfas.github.io/gestalten-in-code/grid/network-of-molecules

**Comment by vogelino** [comment]
Here is a minified version of the script:
[molecular-networks-p5-algorithm-bundled.zip](https://github.com/vogelino/molecular-networks-p5-algorithm/files/474169/molecular-networks-p5-algorithm-bundled.zip)

**Comment by ff6347** [comment]
ähm. Thank you  but that's not what I meant. It would be cool to have a version without p5.js integrated and without styl and all that. Just the algorithm. But that would mean a rewrite to ES5 so no compilation is needed

**Comment by vogelino** [comment]
Oh yeah I get it. Unfortunately this would mean too much work for me to rewrite everything in es5. Feel free to do it if you want, but unfortunately I do not have time for that. Sorry about that.

**Comment by ff6347** [comment]
No. me neither. I already took a look at it but it is so much ES6 with wired classes and what not. :-)

**Comment by vogelino** [comment]
Yeah. Sorry about that but I never loose an occasion to test the most features of es2015 when I can! Haha
